controller_manager:
  ros__parameters:
    update_rate: 50 
    use_sim_time: true
    
    gazebo_differencial_drive_controller:
      type: "diff_drive_controller/DiffDriveController"
      ros__parameters:
        left_wheel: ["left_wheel_joint"]
        right_wheel: ["right_wheel_joint"]

        wheel_separation: 0.17
        #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
        wheel_radius: 0.032

        wheel_separation_multiplier: 1.0
        left_wheel_radius_multiplier: 1.0
        right_wheel_radius_multiplier: 1.0

        publish_rate: 50.0
        odom_frame_id: odom
        base_frame_id: base_footprint
        pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
        twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

        open_loop: true
        enable_odom_tf: true

        cmd_vel_timeout: 0.5
        #publish_limited_velocity: true
        use_stamped_vel: false
        #velocity_rolling_window_size: 10
        linear:
          x:
            has_velocity_limits    : true
            max_velocity           : 0.2   # m/s
            has_acceleration_limits: true
            max_acceleration       : 0.6   # m/s^2
        angular:
          z:
            has_velocity_limits    : true
            max_velocity           : 2.0   # rad/s
            has_acceleration_limits: true
            max_acceleration       : 6.0   # rad/s^2