# costmap_common_params.yaml
obstacle_range: 2.5
raytrace_range: 6.0
transform_tolerance: 0.2
robot_radius: 0.2
inflation_radius: 0.3
observation_sources: scan
map_type: costmap
robot_base_frame: base_footprint
cost_scaling_factor: 3.0

scan: 
  sensor_frame: laser_link
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]




